name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
        node: ['10', '12']
        laravel: ['6.*', '7.*', '8.*']
        prefer: ['prefer-lowest', 'prefer-stable']
        include:
          - laravel: '6.*'
            testbench: '4.*'
          - laravel: '7.*'
            testbench: '5.*'
          - laravel: '8.*'
            testbench: '6.*'

    name: PHP ${{ matrix.php }} - Node ${{ matrix.node }} - Laravel ${{ matrix.laravel }} --${{ matrix.prefer }}

    steps:
    - uses: actions/checkout@v1

    - name: Install Chromium binary
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3 chromium-browser

    - name: Test Chromium binary
      run: |
        /usr/bin/chromium-browser --version

    - uses: actions/setup-node@v2-beta
      name: Install Node.js
      with:
        node-version: '${{ matrix.node }}'

    - name: Test Node.js binary
      run: |
        node -v

    - uses: actions/cache@v1
      name: Cache Composer dependencies
      with:
        path: ~/.composer/cache/files
        key: composer-php-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.prefer }}-${{ hashFiles('composer.json') }}

    - uses: actions/cache@v1
      name: Cache Node.js dependencies
      with:
        path: node_modules/
        key: node-js-${{ matrix.node }}-${{ hashFiles('package.json') }}

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --${{ matrix.prefer }} --prefer-dist --no-interaction --no-suggest
        npm install --only=prod

    - name: Run tests
      run: |
        phpunit --coverage-text --coverage-clover=coverage.xml

    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: screenshots
        path: artifacts/screenshots

    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
